CREATE TABLE IF NOT EXISTS PUBLIC.COTACOES (
  ID              BIGSERIAL PRIMARY KEY,
  ATIVO           VARCHAR(10) NOT NULL,
  PRECO           NUMERIC(15, 6) NOT NULL,
  MOEDA           CHAR(3) NOT NULL,
  HORARIO_COLETA  TIMESTAMP NOT NULL,
  DATA_CRIACAO    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)